/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Utils/Logger.h"
/* Header for class yizheneng_Utils_JniLogger */

#ifndef _Included_yizheneng_Utils_JniLogger
#define _Included_yizheneng_Utils_JniLogger
#ifdef __cplusplus
extern "C" {
#endif
#undef yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_DEBUG
#define yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_DEBUG 0L
#undef yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_INFO
#define yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_INFO 1L
#undef yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_WARN
#define yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_WARN 2L
#undef yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_ERROR
#define yizheneng_Utils_JniLogger_JNI_LOGGER_LEVEL_ERROR 3L
/*
 * Class:     yizheneng_Utils_JniLogger
 * Method:    loggerToJni
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yizheneng_Utils_JniLogger_loggerToJni
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
